# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 655fe8a47d99aabd4084ce4f43d8d1a09680088798f99fc1cb2261b8f593d23e32eea46b33f42583ec5a9ad082983f6a4c7f8dbda8f12433821ee03f12499519

test:
  secret_key_base: 199d115591bf2df09e9d0f46a45445544dd6d89e9d4c744fe91bf2696eb641b5e3e6707a8eb30585932497fbf99e28e3fd58d649cde8e92c941a5925fa53f4c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
